# Soluzione sistemi lineari.

26/10/2015

docente: Francesca Mazzia

Il materiale è distribuito con licenza Creative Commons Attribuzione-Non commerciale-Non Opere Derivate 2.5 Italy License http://creativecommons.org/licenses/by-nc-nd/2.5/it/

### Matrici e Vettori

Scriviamo una matrice casuale con 3 righe  4 colonne 


In [2]:
import numpy as np
from __future__ import print_function

# np.random.rand genera numeri casuali appartenenti a una distribuzione uniforme
A = np.random.rand(3,4)*10
print(A)

[[ 3.99844743  9.25402689  2.71911036  3.95726006]
 [ 6.4112549   1.07740481  6.34566677  1.68902294]
 [ 8.54240964  2.08524755  3.25146472  9.0407741 ]]


In [4]:
# questa e' una matrice rettangolare
# scriviamo una matrice quadrata con elementi casuali interi
A = np.random.randint(10,size=(3,3))
print(A)

[[6 7 7]
 [3 2 4]
 [5 3 7]]


In [5]:
# gli elementi delle matrici si denotano
# usando l'indice di riga e di colonna
print(A[0,0])
print(A[1,1])
print(A[2,2])

6
2
7


In [6]:
print(type(A))

<type 'numpy.ndarray'>


Trasposta

In [7]:
print('trasposta\n',A.T)

trasposta
 [[6 3 5]
 [7 2 3]
 [7 4 7]]


Prodotto riga per colonne e prodotto fra matrici

In [9]:
print(np.dot(A,A))
print(A*A)

[[ 92  77 119]
 [ 44  37  57]
 [ 74  62  96]]
[[36 49 49]
 [ 9  4 16]
 [25  9 49]]


Tipo matrix

In [10]:
A = np.asmatrix(A)
print(A)    
print('classe matrice A = ',type(A)) # A di tipo matrix
print('---- Matrice inversa ----')
print(A.I)     # A.I inversa di A
print('---- Prodotto riga per colonne A.I*A ----')
print(A.I*A)    # il * e' il prodotto riga per colonne
print('---- Prodotto riga per colonne A.I*A con np.dot----')
print(np.dot(A.I,A))

[[6 7 7]
 [3 2 4]
 [5 3 7]]
classe matrice A =  <class 'numpy.matrixlib.defmatrix.matrix'>
---- Matrice inversa ----
[[ -1.   14.   -7. ]
 [  0.5  -3.5   1.5]
 [  0.5  -8.5   4.5]]
---- Prodotto riga per colonne A.I*A ----
[[  1.00000000e+00   3.55271368e-15   7.10542736e-15]
 [ -8.88178420e-16   1.00000000e+00  -1.77635684e-15]
 [  0.00000000e+00   1.77635684e-15   1.00000000e+00]]
---- Prodotto riga per colonne A.I*A con np.dot----
[[  1.00000000e+00   3.55271368e-15   7.10542736e-15]
 [ -8.88178420e-16   1.00000000e+00  -1.77635684e-15]
 [  0.00000000e+00   1.77635684e-15   1.00000000e+00]]


In [11]:
U=np.triu(A)   # operazioni con in input matrix in output array
print(type(U)) # la classe di U uguale alla classe  di A
print(U)

<class 'numpy.matrixlib.defmatrix.matrix'>
[[6 7 7]
 [0 2 4]
 [0 0 7]]


In [13]:
A.shape  # numero di righe e colonne

(3, 3)

In [14]:
A.ndim  # dimensione della matrice, possiamo avere array a piu' dimensioni

2

In [15]:
O = np.zeros( (3,3) ) # matrice nulla
print(O)
print(type(O))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
<type 'numpy.ndarray'>


In [16]:
I = np.eye(3) # matrice identità
print(type(I))
print(I)

<type 'numpy.ndarray'>
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [17]:
d = np.diag(np.array([1, 2, 3, 4])) # array con elementi sulla diagonale
print(d)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [18]:
narray = np.arange(1,10,2) # arange array
print(narray)

[1 3 5 7 9]


In [21]:
B = np.empty((3,4) ) # array vuoto non inizializzato
print(B)

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [22]:
a = np.arange(10) 
print(a)
print('--- Ordine inverso degli elementi di a ---')
print(a[::-1])      # ordine inverso

[0 1 2 3 4 5 6 7 8 9]
--- Ordine inverso degli elementi di a ---
[9 8 7 6 5 4 3 2 1 0]


In [24]:
a = np.arange(10000)
%timeit a + 1  

10000 loops, best of 3: 43.9 µs per loop


In [26]:
l = range(10000)
%timeit [i+1 for i in l] 

1000 loops, best of 3: 1.19 ms per loop


In [27]:
 a = np.array([1, 2, 3, 4])
 b = np.array([4, 2, 2, 4])
 a == b


array([False,  True, False,  True], dtype=bool)

In [28]:
a > b


array([False, False,  True, False], dtype=bool)

In [29]:
 np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [30]:
np.sin(a[0])

0.8414709848078965

In [31]:
import scipy as sp


In [32]:
import  linalgmod
import  time

dim=150
A=np.random.rand(dim,dim)
B=np.random.rand(dim,dim)
#import importlib as imp
#imp.reload(linalgmod)  #per ricaricare il modulo se si fanno modifiche

In [33]:
t1=time.clock()
C1=linalgmod.prodmatmat(A,B)
t2=time.clock()-t1
print( "clock = ", t2 )

 
# A e B sono array il prodotto riga per colonne si esegue utilizzando 
# np.dot
t1=time.clock()
C2=np.dot(A,B)
t2d=time.clock()-t1
print( "clock = ", t2d )


print( "errore", np.max(np.abs(C1-C2)) )

# C1 e C2 contengono gli stessi elementi


clock =  8.23363081062
clock =  0.00308838134455
errore 0.0


In [34]:
import scipy.linalg as la
# la function inv calcola l'inversa di A 
print('matrice inversa') 
AI = la.inv(A)
print(AI)
print('---- Prodotto riga per colonne AI*A ----')
print( np.dot(AI,A) ) 

matrice inversa
[[ 0.40848257  0.18681418  0.08343176 ...,  0.15476732  0.54997619
  -0.92574624]
 [ 0.17110084  0.2427972   0.27060567 ...,  0.03829957  0.85705479
  -0.39716242]
 [-0.33315096 -0.27046257 -0.16761542 ..., -0.19642685 -1.30227038
   0.92608898]
 ..., 
 [-0.4946256  -0.63027002 -0.33710292 ..., -0.52188077 -1.53767583
   1.57749111]
 [-0.07619781  0.51002937  0.46685882 ...,  0.3026069   0.24182703
  -0.60343406]
 [-0.13911309  0.03027829  0.01831819 ...,  0.03685295 -0.57046689
   0.14259538]]
---- Prodotto riga per colonne AI*A ----
[[  1.00000000e+00  -2.77555756e-16   1.66533454e-16 ...,   4.44089210e-16
    1.49880108e-15   1.11022302e-15]
 [ -1.69309011e-15   1.00000000e+00  -7.49400542e-16 ...,  -4.97518693e-15
   -4.38538095e-15  -1.66533454e-16]
 [ -9.99200722e-16  -1.55431223e-15   1.00000000e+00 ...,   2.94209102e-15
    3.71924713e-15  -1.66533454e-14]
 ..., 
 [  1.99840144e-15  -4.99600361e-16   1.55431223e-15 ...,   1.00000000e+00
    5.55111512e-15  -9.32

In [35]:
# una matrice che non ha inversa si dice
# singolare
print('--- determinante di A ---')
print(la.det(A)) #  det calcola il determinate di A

--- determinante di A ---
1.16959018005e+51


In [36]:
A = np.random.rand(3,4)
# norma di Frobenious  \sqrt{ \sum_{i=1}^n \sum_{j=1}^m a_{ij}^2 }
print('norma frobenious= ',la.norm(A) )
# norma 1
n1 = la.norm(A,1)
print('norma 1 = ',n1)
# norma infinito
ninf = la.norm(A,np.inf)
print('norma infinito = ',ninf)
# norma 2
n2= la.norm(A,2)
print('norma 2 = ',n2 )
# rango di A
print('rango di A =', np.linalg.matrix_rank(A))

norma frobenious=  1.63772815585
norma 1 =  1.52341682945
norma infinito =  2.02572325649
norma 2 =  1.523502374
rango di A = 3


In [ ]:
a=np.array([-4, -3, -2, -1,  0,  1,  2,  3,  4])
print(a)
b = a.reshape((3, 3))
print(b)

Sistema lineare: trovare  x tale che A*x = b

In [38]:
np.lookfor('solve linear system')

Search results for 'solve linear system'
----------------------------------------
numpy.linalg.solve
    Solve a linear matrix equation, or system of linear scalar equations.


In [42]:
A = np.random.rand(3,3)
b = np.array([1,2,3])
x = np.linalg.solve(A,b)
print(x)
type(x)
print( np.dot(A,x)-b)

[ 1.38308468  6.97965318 -1.21510349]
[  4.44089210e-16   0.00000000e+00   0.00000000e+00]


In [43]:
print('classe di A =',type(A))
print('residuo =', np.dot(A,x)-b) # residuo

classe di A = <type 'numpy.ndarray'>
residuo = [  4.44089210e-16   0.00000000e+00   0.00000000e+00]


In [45]:
# i vettori array non sono differenziati per vettori riga o colonna
print(x.shape)
y = x.T
print(y.shape)

print(A*x)
print(A*y-A*x)
print(' A = ', A)
print(' x = ', x)
print( A[:,0]*x[0])
print( A[:,1]*x[1])
print( A[:,2]*x[2])


(3,)
(3,)
[[ 0.08848589  2.00512841 -1.0936143 ]
 [ 0.01841231  2.30610313 -0.32451545]
 [ 0.86546117  3.06206067 -0.92752184]]
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
 A =  [[ 0.0639772   0.28728196  0.90001742]
 [ 0.0133125   0.33040369  0.26706816]
 [ 0.62574706  0.43871244  0.76332744]]
 x =  [ 1.38308468  6.97965318 -1.21510349]
[ 0.08848589  0.01841231  0.86546117]
[ 2.00512841  2.30610313  3.06206067]
[-1.0936143  -0.32451545 -0.92752184]


Soluzione di Sistemi lineari con matrice dei coefficienti triangolare
inferiore:


In [51]:
#definiamo la function
def solL(L,b):
    """
    Soluzione sistemi con matrice dei coefficienti
    triangolare inferiore, implementazione per righe
    INPUT  = matrice L, termine noto b
    OUTPUT = soluzione x
    
    """
    (n,m) = np.shape(b)
    x = np.zeros((n,1))
    x[0]=b[0]/L[0,0]
    for i in range(1,n):
        x[i]=(b[i] - np.dot(L[i,0:i],x[0:i]))/L[i,i]
    return x

n=20
L  = np.tril(np.random.rand(n,n))
xt = np.ones((n,1))
b  = np.dot(L,xt)
x  = solL(L,b)
print('x')
print(x)
print('errore assoluto')
print( abs(x-xt))

x
[[ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]
 [ 1.]]
errore assoluto
[[  0.00000000e+00]
 [  0.00000000e+00]
 [  4.44089210e-16]
 [  5.55111512e-16]
 [  3.33066907e-16]
 [  6.66133815e-16]
 [  8.88178420e-16]
 [  8.88178420e-16]
 [  1.38777878e-14]
 [  9.99200722e-15]
 [  2.75335310e-14]
 [  5.10702591e-15]
 [  4.97379915e-14]
 [  3.79696274e-14]
 [  3.58602037e-14]
 [  4.90718577e-14]
 [  2.64233080e-14]
 [  1.90736316e-13]
 [  2.08055795e-13]
 [  2.66453526e-15]]


In [52]:
A0= np.matrix( [[4., 0, 1., 1.], 
[3., 1., 3., 1.],
[0, 1., 2., 0],
[2., 2., 4., 1.]])
# copio la matrice A0 in A
A=np.asmatrix(np.copy(A0))
print(A)

[[ 4.  0.  1.  1.]
 [ 3.  1.  3.  1.]
 [ 0.  1.  2.  0.]
 [ 2.  2.  4.  1.]]


In [53]:

# n contiene il numero di righe di A
n=A.shape[0]
#%%
# inizializzo L
L = np.asmatrix(np.zeros([n,n]))
#%%
# inizializzo P
P=np.asmatrix(np.eye(n))
print(P)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [54]:
# scegliamo il pivot

indm=np.argmax(np.abs(A[:,0]))
print(indm)
# scambiamo le righe di A
A[ [0,indm],:]=A[[indm,0],:]
print(A)
   
# scambiamo le righe di P 
P[ [0, indm],:]=P[[indm,0],:]
print(P)

0
[[ 4.  0.  1.  1.]
 [ 3.  1.  3.  1.]
 [ 0.  1.  2.  0.]
 [ 2.  2.  4.  1.]]
[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


In [55]:
# calcolo gli elementi di L 
L[1:n,0]=A[1:n,0]/A[0,0]

# calcolo la U  riscrivendola in A
# aggiorno la seconda riga a blocchi
# 
A[1:n,1:n]=A[1:n,1:n]-(L[1:n,0]*A[0,1:n])
A[1:n,0]=0
print(A)

[[ 4.    0.    1.    1.  ]
 [ 0.    1.    2.25  0.25]
 [ 0.    1.    2.    0.  ]
 [ 0.    2.    3.5   0.5 ]]


In [56]:
# verifichiamo
print(P*A0 - (L+np.eye(n))*A)
#%%

[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [57]:
# ripeto il procedimento sulla sottomatrice  A(1:n,1:n)

indm=np.argmax(abs(A[1:n,1]))
indm = indm+1
# scambiamo le righe di A
A[ [1, indm],:]=A[[indm,1],:]
# scambiamo le righe di P 
P[ [1, indm],:]=P[[indm,1],:]
# scambiamo le righe di L
L[ [1, indm],:]=L[[indm,1],:]
# calcolo gli elementi di L 
L[2:n,1]=A[2:n,1]/A[1,1]
print( ' -- matrice L dopo aggiornamento --')
print(L)
# calcolo la U  riscrivendola in A
# 
A[2:n,2:n]=A[2:n,2:n]-L[2:n,1]*A[1,2:n]
A[2:n,1]=0
print( ' -- matrice U dopo aggiornamento --')
print(A)
# verifichiamo
print('-- verifica --')
print(P*A0 - (L+np.eye(n))*A)

 -- matrice L dopo aggiornamento --
[[ 0.    0.    0.    0.  ]
 [ 0.5   0.    0.    0.  ]
 [ 0.    0.5   0.    0.  ]
 [ 0.75  0.5   0.    0.  ]]
 -- matrice U dopo aggiornamento --
[[ 4.    0.    1.    1.  ]
 [ 0.    2.    3.5   0.5 ]
 [ 0.    0.    0.25 -0.25]
 [ 0.    0.    0.5   0.  ]]
-- verifica --
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


In [58]:

indm=np.argmax(abs(A[2:n,2]))
print('indm = ',indm)
indm = indm+2
print('indm = ',indm)
# scambiamo le righe di A
A[ [2, indm],:]=A[[indm,2],:]
print( ' -- matrice A dopo permutazioni --')
print(A)   
# scambiamo le righe di P 
P[ [2, indm],:]=P[[indm,2],:]
print( ' -- matrice P dopo permutazioni --')
print(P)
# scambiamo le righe di L
L[ [2, indm],:]=L[[indm,2],:]
print(' -- matrice L dopo permutazione --')
print(L)
# calcolo gli elementi di L 
L[3:n,2]=A[3:n,2]/A[2,2]
print(' -- matrice L --')
print(L)
# calcolo la U  riscrivendola in A
# 
A[3:n,3:n]=A[3:n,3:n]-L[3:n,2]*A[2,3:n]
A[3:n,2]=0
print( ' matrice U ')
print(A)
# verifichiamo
print(' --- verifica ---')
print(P*A0 - (L+np.eye(n))*A)
L= L+np.eye(n)
U=A

indm =  1
indm =  3
 -- matrice A dopo permutazioni --
[[ 4.    0.    1.    1.  ]
 [ 0.    2.    3.5   0.5 ]
 [ 0.    0.    0.5   0.  ]
 [ 0.    0.    0.25 -0.25]]
 -- matrice P dopo permutazioni --
[[ 1.  0.  0.  0.]
 [ 0.  0.  0.  1.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]
 -- matrice L dopo permutazione --
[[ 0.    0.    0.    0.  ]
 [ 0.5   0.    0.    0.  ]
 [ 0.75  0.5   0.    0.  ]
 [ 0.    0.5   0.    0.  ]]
 -- matrice L --
[[ 0.    0.    0.    0.  ]
 [ 0.5   0.    0.    0.  ]
 [ 0.75  0.5   0.    0.  ]
 [ 0.    0.5   0.5   0.  ]]
 matrice U 
[[ 4.    0.    1.    1.  ]
 [ 0.    2.    3.5   0.5 ]
 [ 0.    0.    0.5   0.  ]
 [ 0.    0.    0.   -0.25]]
 --- verifica ---
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]


Esercizio: scrivere una function che data una matrice A in input, esegue la fattorizzazione LU con pivot parziale. 

Risolviamo un sistema lineare con matrice dei coefficienti
la matrice di Hilbert.La matrice viene costruita nel modulo linalgmod.
Il termine noto lo scegliamo in modo che la soluzione x
sia il vettore di tutti  uno.

In [65]:
n = 20
A = linalgmod.hilb(n)
#print(A)
x = np.ones( (n,1))
b = np.dot(A,x)
#print(b)

risolviamo il sistema, calcoliamo il residuo e l'errore assoluto

In [66]:
xa = np.linalg.solve(A,b)
xb = la.solve(A,b)

In [67]:
print(la.norm(x-xa,2))
print(la.norm(x-xb,2))

326.396081414
326.396081414


Stampiamo il numero di condizione di A. Il numero di condizione nella soluzione di un sistema lineare ci dice come una perturbazione sui dati di input (A e b) si ripercuote sul risultato (xa). Il numero di condizione $$\kappa(A) = \| A \| \| A^{-1}\|$$ 

In [ ]:
np.linalg.cond(A)

la matrice di Hilbert è mal condizionata

In [ ]:
Possiamo anche prima fattorizzare la matrice a poi risolvere i sistemi
lineari usando la fattorizzazione. La fattorizzazione usata dagli 
algoritmi classici è la fattorizzazione LU con pivot

In [ ]:
#%%
# function lu di scipy
p,l,u=la.lu(A)
la.norm(A-np.dot(np.dot(p,l),u),1)


In [ ]:
np.linalg.cond(l)

In [ ]:
np.linalg.cond(u)

In [ ]:
# function lu della libreria lapack
x1=la.solve(A,b)
lu,piv=la.lu_factor(A)
# piv contiene il vettore delle permutazioni
# la riga i e' stata cambiata con la riga piv[i


In [ ]:
x2=la.lu_solve((lu,piv),b)
la.norm(x2-x,2)

visualizziamo il residuo. Un residuo piccolo non implica un errore piccolo se la matrice è mal condizionata.

In [ ]:
la.norm(np.dot(A,x2)-b,2)